### ISSUE TITLE
Default layer only

### ISSUE THREAD

**Issue by lukakostic** [keijiro/KvantStream#2]
No matter what layer i put the particle emitter object on, it seems to always be on default layer. If i turn of defaul layer culling on my camera i cant see the particles.

**Comment by lukakostic** [comment]
Hey could you tell me if this will be an easy fix and will be fixed soon or if its hard and wont be fixed soon?
I am planning to use this in a project and im expecting to use the layers to display the particles while hiding everything else.
I dont have any other optimal way of rendering just the particles other than putting them on a seperate layer and rendering only that layer.

**Comment by keijiro** [comment]
Please try changing this line:

https://github.com/keijiro/KvantStream/blob/3332a13edb6db9eca93064e2b64f8e334d0b80a3/Assets/Kvant/Stream/Stream.cs#L342

like the following:

```
Graphics.DrawMesh(_mesh, transform.position, transform.rotation, _lineMaterial, gameObject.layer);
```

I think this fixes the problem but I don't have time for testing.

**Comment by lukakostic** [comment]
Yep works now

**Comment by lukakostic** [comment]
Changed the stream file in the repository to fix, you can accept or whatever the pull or change it yourself and delete the pull or something
